# .build.yml -- builds.sr.ht CI/CD
image: openbsd/latest
sources:
    - https://git.sr.ht/~akarle/euchre-live
packages:
    - p5-Mojolicious
    - p5-Class-Tiny
tasks:
    - test: |
        cd euchre-live
        make test
triggers:
    - action: email
      condition: always
      to: ci@alexkarle.com
