# .build.yml -- builds.sr.ht CI/CD
image: debian/stable
packages:
    - cpanminus
sources:
    - https://git.sr.ht/~akarle/euchre-live
environment:
    PERL5LIB: /home/build/perl5/lib/perl5
tasks:
    - setup: |
        cd euchre-live
        cpanm --installdeps .
    - test: |
        cd euchre-live
        make test
triggers:
    - action: email
      condition: always
      to: alex@karle.co
